# Generated by Django 3.0.6 on 2020-05-18 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=64)),
                ('crm', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('especialidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Especialidade')),
            ],
        ),
    ]
